### ISSUE TITLE
[Frontend] The user is forced to withdraw on Ethereum - Better UX

### ISSUE THREAD

**Issue by DOBEN** [Concordium/eth-ccd-bridge#101]
**Description**

The user is forced to withdraw on Ethereum and front-end can't be used for anything else. This is bad UX.

In the example, when initiating the withdrawal of 1 SHIB token (since this is probably not worth claiming on Ethereum - gas costs are high), the user might change their mind and not want to complete a specific withdrawal.

Suggestion: 
Show pending withdrawals, with a call-for-action to the withdrawals history page to complete the withdrawal.

**Comment by mh-concordium** [comment]
Tested on version 1.0.0.

@soerenbf  Looking at this page, what should I do next? How do I approve withdrawal?

![image.png](https://images.zenhubusercontent.com/6284893f971a3daf4db6e569/592c71bf-a9f0-4e68-8ae2-ab080550b6aa)

**Comment by soerenbf** [comment]
Will change the status of "ready for approval" withdrawals to "Approve" + change the color of pending (but not ready for approval) transactions to gray.

**Comment by mh-concordium** [comment]
Verified in version 1.0.1.
