### ISSUE TITLE
[Frontend] Submitted withdrawals are not shown when page is loaded in a different tab

### ISSUE THREAD

**Issue by DOBEN** [Concordium/eth-ccd-bridge#103]
**Task description**

The number of withdrawals that are shown is different. In the example, one withdrawal is shown as “submitted” on the bridge page that initiated the withdrawal but it is not shown anymore when loading the bridge page in a new tab

https://concordium.slack.com/archives/C04CV1DM0NM/p1680689384724899

**Comment by mh-concordium** [comment]
Verified.
Version: 1.0.0
