### ISSUE TITLE
[Frontend] Wrong label/amount shown on transfer progress page

### ISSUE THREAD

**Issue by soerenbf** [Concordium/eth-ccd-bridge#116]
**Bug Description**

The frontend can get in a state where it prioritizes values stored for a transaction flow over values recorded and stored for the actual transaction in the backend. This leads to wrong information sometimes being shown on the transfer progress page.

**Steps to Reproduce**

- Have an account connected with transactions in the transaction history.
- Select a token and amount on the front page and press continue
- Go to the transaction history, and click on a transaction with another token/amount
- The information displayed on the transfer progress page should be wrong at this point

**Expected Result**

The right information is shown

**Actual Result**

The wrong information is shown.

**Versions**
- Software Version: 1.0.1
- Browser Chrome

**Comment by mh-concordium** [comment]
Verified in 1.0.2.
I have also just tried one deposit and one withdrawal as a small regression check.
