### ISSUE TITLE
[Frontend] Wrong network (Concordium side)

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#62]
**Bug Description**
If user visits frontend while Mainnet is selected, frontend doesn't show any issues. 

**Steps to Reproduce**
Visit bridge front-end with Concordium browser wallet installed but e.g. mainnet is selected in wallet network setting.

**Expected Result**
Frontend should point to the user that the network is wrong.

**Actual Result**
Nothing happens.

**Versions**
- Software Version:0.1.0

**Comment by soerenbf** [comment]
This is fixed in #93, but will only work when v1.0 of concordium browser wallet is released.

**Comment by DOBEN** [comment]
Tested successfully.
