### ISSUE TITLE
[Frontend] Attempt to connect while on wrong network (Concordium side)

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#63]
**Bug Description**
If user tries to connect while Mainnet is selected, frontend doesn't show any issues. 

**Steps to Reproduce**
1. Visit bridge front-end with Concordium browser wallet installed and with correct network selected in wallet network setting.
2. Switch the network to the wrong one (Mainnet in this case).
3. Select Connect in the frontend.

**Expected Result**
Frontend should point to the user that the network is wrong. 

**Actual Result**
Nothing happens.

**Versions**
- Software Version:0.1.0

**Comment by DOBEN** [comment]
Tested successfully.
