### ISSUE TITLE
[Frontend] Attempt to connect while on wrong network (Ethereum side)

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#64]
**Bug Description**
If user tries to connect while wrong network is selected, frontend doesn't show any issues. 

**Steps to Reproduce**
1. Visit bridge front-end with MetaMask browser wallet installed and with correct network selected in wallet network setting.
2. Switch the network to the wrong one (Mainnet in this case).
3. Select Connect in the frontend.

**Expected Result**
Frontend should point to the user that the network is wrong. 

**Actual Result**
Frontend doesn't provide any feedback. One can approve connection in MetaMask and proceed one more step after which MetaMask asks user to switch the network because it is wrong one.

**Versions**
- Software Version:0.1.0

**Comment by soerenbf** [comment]
Implemented this by requesting a network change to the correct network if the wrong network is selected in the wallet.

**Comment by DOBEN** [comment]
Tested successfully.
