### ISSUE TITLE
[Frontend] Try to bridge an amount greater than your balance

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#65]
**Bug Description**
Add error message for attempt to deposit more tokens than there is on the balance.

**Steps to Reproduce**
Attempt to deposit more tokens than there is on your balance.

**Expected Result**
Error message.

**Actual Result**
Value that was inserted to be deposited is marked in red.

**Versions**
- Software Version: 0.1.0

**Comment by DOBEN** [comment]
Tested successfully.
