### ISSUE TITLE
[Frontend] List of tokens improvements

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#66]
**Bug Description**
Add fixes to the list of tokens as agreed:

1. Order the list of tokens alphabetically.
2. Add correct icons to the list.

**Steps to Reproduce**
Open the list of tokens in the frontend.

**Expected Result**
Order the list of tokens alphabetically.
Add correct icons to the list.

**Actual Result**
List is not ordered and it is one icon for all the tokens.

**Versions**
- Software Version: 0.1.0

**Comment by soerenbf** [comment]
Blocked until #72 is implemented

**Comment by DOBEN** [comment]
Tested successfully.
