### ISSUE TITLE
[Frontend] Fix the "max button"

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#67]
**Bug Description**
Max button doesn't work as expected, it doesn't input the max balance to the field.

As a note, maybe we have to consider some special handling in case of bridging ETH since gas would need to be deducted.

**Steps to Reproduce**

1. Connect your test wallet with some ETH.
2. Connect your CCD wallet.
3. Select ERC20_token and press max button.

**Expected Result**
Number of all the tokens appear in the field to be deposited.

**Actual Result**
Number is to large. So large, deposit is not allowed.

**Versions**
- Software Version: 0.1.0

**Comment by DOBEN** [comment]
Tested successfully.
