### ISSUE TITLE
[Frontend] Frontend doesn't get updated if the focus is not on the page

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#70]
**Bug Description**
If focus is not on the Frontend, it doesn’t get updated, it stays the same until you click on the frontend.

**Steps to Reproduce**
Make a deposit, then when the screen with the sand clock appears move focus away to other screen.

**Expected Result**
Frontend should get updated as the deposit gets processed.

**Actual Result**
Frontend gets updated only if user clicks back on the page. As long as the focus is not on the page, the Frontend doesn't get updated.

**Versions**
- Software Version: 0.1.0

**Comment by DOBEN** [comment]
Tested successfully.
