### ISSUE TITLE
[Frontend] Show all digits in the balance

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#71]
**Bug Description**
It seems that we use rounding rather than showing all the digits of the current balance of the connected wallet.

**Steps to Reproduce**

1. Connect MetaMask that has ETH balance in 18 digits after decimal point.
2. Check your balance in the frontend.
3. Make a deposit or withdrawal.

**Expected Result**
All the 18 decimals after the decimal point are shown trough the whole frontend.

**Actual Result**
Balance is rounded to 4 decimals trough the whole frontend.
Notice that 4 decimals are shown also in the progress view.

**Versions**
- Software Version: 0.1.0

**Note**
This issue is example with ETH that has 18 digits. For tokens that have 8 or 6 digits it would be expected to show that number of digits.

**Comment by DOBEN** [comment]
Tested successfully.
