### ISSUE TITLE
[Frontend] Token is not persisted on the list after canceling on deposit overview

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#76]
**Bug Description**
In case if  https://ethbridgeapp.testnet.concordium.com/?reset=true and user selects Cancel on the Deposit Overview, user is returned to the previous screen but token selection from the list is not persisted.

**Steps to Reproduce**

1. Visit https://ethbridgeapp.testnet.concordium.com/?reset=true
2. Connect wallets .
3. Select token to deposit.
4. Select Cancel in Deposit Overview.

**Expected Result**
User is returned to the Transfer page and token is still selected on the list os that user can only adjust the value.

**Actual Result**
It is necessary to select the token again.

**Versions**
- Software Version: 0.1.0

**Comment by DOBEN** [comment]
Tested successfully.
