### ISSUE TITLE
[Frontend] Withdrawal history list is not ordered

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#81]
**Bug Description**
It seems that deposits history tab list is ordered by time. Withdraws history tab list is not ordered.

**Steps to Reproduce**
1. Make multiple withdrawals and observe the list.

**Expected Result**
Ordered by time maybe the last withdrawal could be the first on the list so that user doesn't need to scroll down.

**Actual Result**
No order.

![image.png](https://images.zenhubusercontent.com/6284893f971a3daf4db6e569/579757ae-c8d2-490e-be2e-a011c78339a3)
**Versions**
- Software Version: 0.7.0

**Comment by DOBEN** [comment]
Tested successfully.
