### ISSUE TITLE
[Frontend] Attempt to deposit more than you have

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#84]
**Bug Description**
Edge case in which user tries to deposit more tokens that available on balance.

**Steps to Reproduce**
1. Have 17 USDT on Metamask.
2. Select to deposit 10 USDT_tokens.
3. Select Continue in the frontend.
4. When MetaMask pops up to confirm don't confirm it, instead, select Cancel in the frontend.
5. Frontend returns to the initial state.
6. Select to deposit 10 USDT_tokens.
7. Select Continue in the frontend.
8. MetaMask will now ask you to confirm both transactions.
9. Confirm one after another.

**Expected Result**
I would assume Frontend would not allow second transaction.

**Actual Result**
For 1 second there was an error printed in the frontend when trying to execute second tx.
Second transaction fails with ` error 'SafeMath: subtraction overflow'`

**Versions**
- Software Version: 0.7.0

**Comment by soerenbf** [comment]
I don't know about this one.. What is described in the steps to reproduce is pretty much leaving metamask in the background, waiting for a user signature, and then trying to shove another transaction on top of that. Metamask will not complain, and I think it's fair that signing both transactions in sequence will result in an error in the latter that causes an overflow?

I really don't want to keep track of pending wallet submissions in the frontend, as that can lead to an even worse state where we completely block users from ever getting to sign transactions (unless they clear their browser storage)

Any thoughts on this @abizjak , @smh1001 , @mh-concordium ?

**Comment by abizjak** [comment]
As I read the issue, it would be solved if the metamask wallet would have API to cancel an invocation.

I agree we should not add too much complexity for this, but if the wallet has an API where you the dApp can tell it to cancel then it seems to me that would be solved.

This would change the expected result. But if the user cancelled then presumably they wanted to cancel the first one.

**Comment by soerenbf** [comment]
> As I read the issue, it would be solved if the metamask wallet would have API to cancel an invocation.
> 
> I agree we should not add too much complexity for this, but if the wallet has an API where you the dApp can tell it to cancel then it seems to me that would be solved.
> 
> This would change the expected result. But if the user cancelled then presumably they wanted to cancel the first one.

I've skimmed through the metamask documentation, and cannot find anything for cancelling a request through the API.

**Comment by abizjak** [comment]
Ok.

Is there any way we can detect that a prompt is open? Or when the user clicks "cancel"  tell them that they should close the metamask prompt before continuing?

If we can just add that text then it is OK for me. If we can block them from proceeding before they have done so that is even better, but that would mean we need to be able to detect whether metamask is open or not.

**Comment by soerenbf** [comment]
Yes. I can't see anything documented on detecting an open metamask window. We can keep some state when we issue a request to metamask to know if there is a pending request or not, but that's the best we can do I'm afraid.

Is this what we want to make of this issue then?

**Comment by abizjak** [comment]
I am not sure what you are recommending. The first message in the thread here is that you don't want to keep state blocking the user. Are you now suggesting to do that?

My ask was, if it is not possible to detect whether the prompt is open or not, to just tell the user when they press cancel. Not to block them from proceeding. It does not seem like that should need extra state other than knowledge of how we got to the page.

**Comment by soerenbf** [comment]
Yeah so I realise it sounds like the same proposal. The first one i meant state persisted in local/session storage for blocking multiple wallet requests at the same time from the bridge, whereas the second would be just in memory (as it would be used just to show an informative message in an alert box or similar when pressing cancel).

Would be easy and pretty harmless to alert when pressing cancel that "You have an open concordium/metamask wallet prompt awaiting signature.", before going back to the page with the input field.

**Comment by abizjak** [comment]
Ok.  Then I think we are talking about the same solution which sounds like the the most sensible option.
