### ISSUE TITLE
[Frontend] It seems that the frontend allows attempt to sign same withdrawal twice on the ETH side

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/eth-ccd-bridge#86]
**Bug Description**
In this edge case, it is possible to initiate attempt to sign same withdrawal twice.

**Steps to Reproduce**
1. Initiate withdrawal and sign it  with CCD BW.
2. Select Continue in frontend, wait for another frontend view for approval.
3. Approve once the UI changes and button appears.
4. MetaMask wallet pops up.
5. While MetaMask is open, close the frontend and open it again
6. Reconnect wallet
7. Approve again as in step 3.
8. Confirm twice in the MetaMask (both transactions)

**Expected Result**
Frontend should prevent user from signing the same withdraw twice.

**Actual Result**
Second transaction fails error` 'RootChainManager: exit already processed'`
Frontend is locked first on approve view then on continue view.

**Versions**
- Software Version: 0.7.0

**Comment by soerenbf** [comment]
There is no good way to prevent this as MetaMask has no API to check if there is a pending request (of any type). One way to prevent this, could be to keep track (in browser localstorage) what's pending approval in a wallet, but I really dislike this approach, as it is prone to spawn future errors that can be much more severe in terms on their effect on user experience.

I think this edge case is going to be so rare, that it can be safely ignored.

What do you think @abizjak, @mh-concordium, @smh1001 ?

**Comment by abizjak** [comment]
I agree. Adding things to local storage is problematic.

Since to reproduce you have to close the frontend and reopen it it is probably going to be very rare.

**Comment by smh1001** [comment]
Agreed
